# Generated by Django 6.0.3 on 2026-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='avatar',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='monedas',
            field=models.IntegerField(default=100),
        ),
    ]
